export const SCREEN_KEYS = {
  MAIN_STACK: 'MAIN_STACK',
  HOME: 'HOME',
  FLEE_CODE: 'FLEE_CODE',
  PHONE_NUMBER: 'PHONE_NUMBER',
  VERIFICATION_CODE: 'VERIFICATION_CODE',
  MY_TRIPS: 'MY_TRIPS',
  REPORTS: 'REPORTS',
  MORE: 'MORE',
  TRIP_DETAILS: 'TRIP_DETAILS',
};
